.run/backend.run.xml, backend/app.py
Updates
```
TermHub API
- Add: Route: concept-set-names, with alias: 'datasets/csets/names'; routes to: /datasets/csets?fields=name
- Add: util: jq_wrapper: For calling JQ from the shell
```
=> Route: Concept set names

backend/app.py, enclave_wrangler/config.py, enclave_wrangler/datasets, enclave_wrangler/objects.py, frontend/src/CSets.js, frontend/src/Table.js, frontend/src/index.js
Updates
```
TermHub Csets
- Update: directory structure
Enclave wrangler
- Update: to use termhub cset dir structure
- Rename: dataset_download.py -> datasets.py
- Rename: dataset_download_new_api -> objects.py
- Update: datasets.py: Now has a 'favorites' param. You can simply pass this and get all of the favorite
datasets downloaded, without needing to pass RIDs or anything, as those are hard coded.
TermHub Frontend
- Rename: ConceptSets -> ConceptSetsPage
- CSets.js misc: (i) Removed some old comments, (ii) general refactoring
- Update: Table: default height calc
- Csets Search page: now displays concepts
TermHub Backend
- Create: New route: datasets/concepts/
```
=> Several updates

backend/app.py, frontend/src/CSets.js, frontend/src/Table.js
Updates
```
Backend
- Update: route /concept-set-overlap-table-data-simple-hierarchy: now shows labels
Frontend
- column width
```
```
TermHub Csets
- Add: Recent commits that have new concept_relationship 'is_a' csv, as well as jupyter notebook changes to make it, and some .gitignore updates.
Backend
- Added route(s) for displaying rows that contain hierarchical data
Frontend
- Updated to use backend updates
```
=> Cset comparison: 1st draft to show off

.run/enclave_wrangler-for-moffit.run.xml, enclave_wrangler/dataset_upload.py, enclave_wrangler/enclave_api.py, enclave_wrangler/utils.py
Updates
```
Enclave Wrangler
- Update: Utils: Added palantire datetime function
- Add: dataset_upload.py: For uploading datasets to Foundry
- Add: enclave_api.py: Lower level functions for working directly with the Foundry REST API.
- Add: Transformation code to go from Moffit format to the Foundry common dataset format.
- Add: .run/ config for moffit dataset
Termhub csets
- Update to include new dirs/files
```
=> Enclave Wrangler: Dataset upload & Moffit transform

README.md, frontend/src/AboutPage.js, frontend/src/ConceptSetCard.js
Updates
```
Documentation
- About page: Refactored to add some simple components
- About page: Added how to about uploading Atlas JSON
- README.md: Added same content as done in 'About page'
Frontend
- About page: docs as described above
- Concept set comparison page: Concept version selected box: the "open in enclave" button now opens the container in the Enclave again. This was done so that there would be less steps people would need to take when uploading Atlas JSON.
```
=> Documentation: atlas json

backend/db/analysis.py, backend/db/initialize.py, backend/db/utils.py, db_backup.sh, enclave_wrangler/models.py, enclave_wrangler/objects_api.py, makefile
DB Counts
- Update: pdated some comments / documentation
- Update: counts_update(): Now the first time that it runs, the delta values are equal to the row counts, rather than being set to 0.
- Add: table 'counts_runs'. It is initalized in initialize.py, and used by counts_update().
- Add: param --note: to counts_update(). Required. Adds context to why the counts were ran at that particular time, e.g. after a backup or a data fetch.
- Bugfix: Fixed situation where table was new and not included in the last counts run. This was resulting in an error when trying to cast an empty pandas.Series to int().
- Update: Docs: (i) db_backup.sh: Includes step instructing to store row counts after doing a backup and reupload of the new backup schema.
- Update: Simplified CLI options
- Bugfix: deltas …
=> DB Counts updates

backend/README.md, backend/db/analysis.py, backend/db/config.py, backend/db/utils.py, backend/utils.py, db_backup.sh, docs/backend/db/analysis.md, makefile, requirements-unlocked.txt, requirements.txt
Updates
- Add: docs/backend/db/analysis.md
- Update: docs/backend/README.md w/ link to the new analysis / db counts markdown file
- Add: analysis.py: --counts-docs: Now saves output to docs/backend/db/analysis.md
- Update: makefile: With corresponding 'counts-docs' command.
- Add: package: tabulate: to Python requirements files
- Bugfix: Changed 'make counts-compare-schemas' back to approximate method now, pending new implementation. It was erroring out.
- Bugfix: db_backup.sh: It was errenously trying to run 'make' commands because of backticks.
- Update: counts/deltas tables: Simplified column headers: timestamps -> 'DATE (N)'
- Bugfix: counts/deltas tables: Ordered columns chronologically
- Update: Added schema param to counts_update()
- Update: counts_compare_schema(): compare_schema …
=> DB Counts update

backend/app.py, backend/db/config.py
Adding functionality to the "DB Refresh" button of the "Help / About" page. Should trigger [this GitHub Action](https://github.com/jhu-bids/TermHub/actions/workflows/refresh_db.yml).
=> DB Refresh Button: Adding functionality

backend/db/analysis.py, backend/db/initialize.py, backend/db/load.py, backend/db/refresh.py, backend/db/reset_and_update.py, backend/db/utils.py, enclave_wrangler/objects_api.py, frontend/src/pages/AboutPage.js, test/test_enclave_wrangler.py
DB refresh / initialize
- Bugfix: Several places in the refresh and initialize scripts were not properly getting/setting DB variables from local database if needed
- Bugfix: Db counts would report on tables we didn't care about or error out if they stopped existing; namely tables that end with _new or _old and are created temporarily as part of the DB refresh process, which could be going on in the background when running counts.
- Bugfix/UX: Filtering out of fetched containers and code sets with 0 members (due usually to the fact that they are new and the enclave releases concept set members more slowly than other data through its API)
Frontend
- Update: help/about page: Changed 'how to fix' section from unordered to ordered list
=> Filtering 0-member code sets

frontend/src/components/FlexibleContainer.js, frontend/src/pages/CsetComparisonPage.js
Popups in the CSET COMPARISON page no longer appear at the same place every time.
When the user tries to open two popups, the second one appears a bit lower and to the right to the first one.
=> Popup positioning

backend/db/refresh.py, backend/db/utils.py, enclave_wrangler/objects_api.py, enclave_wrangler/utils.py
Updates
```
DB Refresh
- Bugfix: Syntax error causing refresh to fail.
- Bugfix: GitHub action was alwasy passing even when it should have shown a failure because exception handling was not re-raising error.
- Bugfix: Minor: Decreased excessive recently added verbosity
- Bugfix: 'None is not iterable': This was caused by unhandled exceptions due to errors being coming from the enclave after pagination handling.
Enclave Wrangler
- Update: Added todo comment to make_objects_request().
```
=> DB Refresh: Syntax error bugfix && other bugfixes

.github/workflows/refresh_db.yml, backend/db/ddl-10-codeset_counts.jinja.sql, backend/db/ddl-11-all_csets.jinja.sql, backend/db/ddl-12-csets_to_ignore.jinja.sql, backend/db/ddl-13-cset_members_items_plus.jinja.sql, backend/db/ddl-14-concept_relationship_plus.jinja.sql, backend/db/ddl-14-concepts_with_counts_ungrouped.jinja.sql, backend/db/ddl-15-concepts_with_counts.jinja.sql, backend/db/ddl-16-concept_relationship_plus.jinja.sql, backend/db/ddl-4-indexes.jinja.sql, backend/db/ddl-6-cset_members_items.jinja.sql, backend/db/ddl-7-concept_ids_by_codeset_id.jinja.sql, backend/db/ddl-8-codeset_ids_by_concept_id.jinja.sql, backend/db/ddl-9-members_items_summary.jinja.sql, backend/db/ddl_deprecated_statements.jinja.sql, backend/db/refresh.py, backend/db/utils.py, enclave_wrangler/objects_api.py
8ecfd6c8c20fda8954aa8cff69f676882b7b3f45
DB Refresh
- Bugfix: Indexes need to be created last. Was throwing error because the index name already exists in the same schema (on the old table not yet deleted). I am unsure why this did not cause an error before. It is possible that maybe indexes were somehow not being created, but that also seems unlikely.
- Update: Reactivated DDL for csets_to_ignore
ef4289b4bd2262cca4e7822c88a9bea96e8452db
DB Refresh
- Update: Changed method of recreating indexes to increase performance.
=> Bugfix: DB refresh index error

.github/workflows/resolve_fetch_failures_excess_items.yml, backend/db/ddl-2-primary_keys.jinja.sql, backend/db/resolve_fetch_failures_0_members.py, backend/db/resolve_fetch_failures_excess_items.py, backend/db/utils.py, enclave_wrangler/models.py, enclave_wrangler/objects_api.py, frontend/src/pages/AboutPage.js, test/backend_tests/db/test_utils.py, test/backend_tests/test_resolve_fetch_failures.py
Addresses issue where we are trying to fetch a brand new concept set that has just been finalized within the last 45 minutes or so, but due to long processes that need to run in the Enclave, its concept set members were not available when we tried to fetch it, so this work will allow for a process that will continuously check until those members appear, and then we will integrate it into the DB.
Updates
DB Refresh: New csets with 0 members
Addresses issue where we are trying to fetch a brand new concept set that has just been finalized within the last 45 minutes or so, but due to long processes that need to run in the Enclave, its concept set members were not available when we tried to fetch it, so this work will allow for a process that will continuously check until those members appear, …
=> DB Refresh: New csets with 0 members

.github/workflows/refresh_voc_and_counts.yml, backend/db/config.py, backend/db/ddl-14-concepts_with_counts_ungrouped.jinja.sql, backend/db/ddl-15-concepts_with_counts.jinja.sql, backend/db/ddl-16-concept_relationship_plus.jinja.sql, backend/db/ddl-17-concept_ancestor_plus.jinja.sql, backend/db/load.py, backend/db/refresh.py, backend/db/refresh_voc_and_counts.py, backend/db/resolve_fetch_failures_0_members.py, backend/db/resolve_fetch_failures_excess_items.py, backend/db/utils.py, docs/developer.md, enclave_wrangler/config.py, enclave_wrangler/datasets.py, enclave_wrangler/objects_api.py, enclave_wrangler/reviving_ontology_api_stuff.py, test/test_enclave_wrangler/test_objects_api.py
Updates
```
DB refresh: Vocab and counts tables
- Add: refresh_voc_and_counts.py
- Add: refresh_voc_and_counts.yml
DB refresh: general
- Update: 0-members script: Added a todo
- Add: DDL for concept_ancestor_plus
- Bugfix: DDL for concept_relationship_plus: An extra comma was causing syntax error
Enclave Wrangler
- Update: Renamed 'FAVORITE_DATASETS' to 'DATASET_REGISTRY' and did the same for similarly named variables.
- Update: Refactored download_datasets() to be easier to understand, less error prone, and more debuggable.t status
- Update: Refactored get_last_update_vocab() to get_last_update_of_dataset(): This function is now general purpose.
- Delete: get_last_update_vocab(): No longer needed. General purpose one was better fit for use in current case.
- Update: …
```
=> DB refresh: Vocab and counts tables

enclave_wrangler/objects_api.py
- Bugfix: 'fetch_failures_0_members' script was not running. The problem was that it was silent failing due to incorrect data type on version_id param; needed to be string.
=> Bugfix: 'fetch_failures_0_members' script

backend/db/queries.py, backend/db/utils.py, backend/routes/db.py, enclave_wrangler/objects_api.py
- Bugfix: PendingRollbackError: When some error happened in our deployment, the DB connection was stuck in a permanent 'pending rollback' state. However, there was no way to roll back without re-deploying. The basic change needed here was that connection objects were being re-used, and were not set up in such a way that they could handle these types of issues. Changed every instance where this was happening to instead set up a new connection if no connection object was passed, rather than initializing the connection within the function definition. This was the source of the problem. The connection object being created within the definition gets created on the first call and is re-used on subsequent calls.
=> Bugfix: Backend perpetually down after connection error

.github/workflows/refresh_db.yml, test/test_database.py
For some reason, the DB refresh is not capturing all new csets. Until we find and fix the root problem (if we ever do), we have a workaround; a function that will find any missing csets and fetch them.
=> Bugfix: Refresh missing csets

backend/db/refresh.py, enclave_wrangler/objects_api.py
- Bugfix: Unhandled case where container ID could not be fetched, and container ID was blank. This was the result of TermHub just recently gaining full access to cset dra
fts. We were fetching all drafts, including ones from when sourceApplicationVersion w
as 1.0 (we're now on 2.0), which was a different data model which had no containers.
Incompatible with TermHub, so we are filtering out and not importing these csets.
See log: https://github.com/jhu-bids/TermHub/actions/runs/6489411749/job/17623626419
```
ValueError: Enclave API returned cset version with container of id , but failed to call data for that specific container.
```
=> Bug: Refresh: Failing on blank container ID

backend/db/refresh.py, backend/db/utils.py
- Bugfix: perpetual refresh: This could happen if the refresh exited in an abnormal way mid-refresh, such as debugging and manually hitting stop. In this case, the code that would normally set refresh status to 'inactive' would not run. Getting around this problem now by using timestamps.
=> Bug: Perpetual "refresh in progress" can occur #574

backend/db/analysis.py, backend/db/utils.py
Fixes bug where temp table could not be dropped because of dependent views.
Bugfix: reset_temp_refresh_tables()
- Bugfix: reset_temp_refresh_tables(): Would error out because could not drop table with dependent views without CASCADE.
- Add: filter_temp_refresh_tables()
- Add: list_views()
=> Bugfix: `reset_temp_refresh_tables()`

backend/db/config.py, backend/db/utils.py
Siggie (and I) tried to do a fix involving refreshing of views. However Siggie felt we either didn't need view or did not need to refresh it, and so tried to deal with that. I cleaned up some of that code, but at the time neither of us realized that this would be insufficient.
I've since fixed the error caused involving views and resetting of table status when refresh fails. I can't remember if Siggie actually wants to get rid of the view(s) or not, so I'm keeping them. I'm just getting rid of the bug that errors out during the reset.
Bugfix: Error on views during DB refresh table reset
- Bugfix: A different PR recently fixed the original bug, but kept the views. But a new bug was introduced, causing the view to sometimes be recognized and sometimes not. This fixes that.
General
- Add: …
=> Bugfix: Follow-up fix for derived views

.github/workflows/refresh_db.yml, backend/db/refresh.py, backend/db/utils.py
- Update: last_refresh_success time now set to 1 microsecond after last_refresh_request, as redundancy in order to ensure that no new data that was added in this timeframe is missed.
- Update: DB refresh action: Deactivated fetch-missing-csets, as various tweaks, including 2 hour re-refresh buffer, and also test-missing-csets, have made this redundant and it just slows down the refresh.
=> `last_refresh_success` fix / redundancy & refresh action tweak

enclave_wrangler/objects_api.py
Bugfix: DB refresh: KeyError: 'archived'
The cause of this was that apparently when you create concept sets in a certain way (I'm guessing via the API), some fields that are normally populated (normally required?) do not get populated, such as 'alias' and 'archived'.
- Bugfix: Now sets 'archived' to False if not detected
- Delete: Some comments
=> Bugfix: refresh: KeyError: 'archived'

.github/workflows/kill_idle_cons.yml, backend/db/utils.py, makefile
Kill idle cons
Kills all idle TermHub related connections older than 10 minutes.
- Add: GitHub action: kill_idle_cons.yml
- Add: Make command: kill-idle-cons
- Add: CLI: backend/db/utils.py --kill-idle-cons
- Add: kill_idle_cons()
=> Kill idle cons

backend/db/initialize.py, backend/db/refresh.py, backend/db/resolve_fetch_failures_0_members.py, enclave_wrangler/objects_api.py
New drafts were sometimes never getting members fetched.
- #520
Bug fixes: fetch_failures_0_members()
- Bug fix: Now does not ignore this issue when the cset is a draft.
- Update: Now does not try to fix the issue mid-refresh because of new param try_fixing_issues_immediately=False. Added comments regarding rationale.
- Update: Now addresses issus at end of refresh if for resolve_fetch_failures_0_members (set to True), but not for resolve_fetch_failures_excess_items (set to False), due to outstanding issues with that action.
- Update: Fetch failures action / script: No longer runs for 2 hours. Just runs once and quits even if it could not fix the issue. Rationale: refresh runs every 20 minutes, so it will try again soon.
- Update: Fetch audit table: add: error_datetime field
- Bug fix: …
=> Bugfixes: `fetch_failures_0_members()`

backend/db/refresh.py, backend/utils.py
Bugfix: GH action triggering
- Bugfix: PAT: This won't be represented in the code, but the personal access token for doing this was not included in the .env.
- Update: Now call_github_action() raises RuntimeError if error received from POST.
=> Bugfix: GH action triggering

backend/db/analysis.py, backend/db/config.py, backend/db/ddl-14-concepts_with_counts.jinja.sql, backend/db/ddl-16-concept_ancestor_plus.jinja.sql, backend/db/ddl-5-concept_set_container.jinja.sql, backend/db/ddl-6-cset_members_items.jinja.sql, backend/db/initialize.py, backend/db/utils.py, test/test_backend/db/test_refresh_dataset_group_tables.py
Bug fix: Vocab refresh error
- Bug fix: Fixed error in which temporary tables were being treated as permanent, which caused error when it tried to manipulate a table that was no longer there.
- Update: Enabled extensions for all schema, so they are available for testing and future proof situations where extension is needed.
- Bug fix: Removed temp tables from config, which was causing them to update when they should not (caused error).
General
- Bug fixes: Jinja updates to SQL DDL, fixing various possible unforeseen current and/or future issues.
- Delete: Some old no-op temp code
=> Bug: Vocab refresh fail: `concept_depth`

backend/db/resolve_fetch_failures_0_members.py, backend/db/utils.py
resolves #757
Discarded drafts
- Bug fix: Discarded drafts no longer are displayed to users.
- Update: Now discarded drafts are deleted from the database.
- Update: Ad hoc script for retroactively checking all existing drafts in the DB (pre-fetch failures) and deleting them from the DB.
General
- Bug fix: Fetch failures success comment was not being set.
- Add: Some comments regarding params for some functions.
=> Bug: Discarded drafts remain

backend/db/refresh.py, backend/db/resolve_fetch_failures_0_members.py, enclave_wrangler/objects_api.py
Bug fixes: Members & expression items not imported
- Bug fix: If drafts had 0 expression items when first fetched, would not trigger follow-up to update the cset later (mainly to import member items).
- Bug fix: After draft finalization, if expression items had changed since first fetch, would not update those expression items.
- Update: Add CLI for DB Refresh to allow fetching by a list of concept IDs.
- Update: Add CLI for "resolve fetch failures 0 members" to force update even if the csets were already marked resolved.
=> Bugfix: Members & expression items not imported

enclave_wrangler/objects_api.py
Bug fix: NULL concept name
- When adding concept_members to the DB, if there was no concept name, would cause an exception.
=> Bug fix: NULL concept name

.github/workflows/refresh_db.yml, backend/db/refresh.py
resolves #832
DB Refresh: Support cset-ids
- Bug fix: Was not setting 'since' to None if cset-ids was present.
- Bug fix: Was passing cset-ids to secondary refresh (if a user requested a refresh from the web app during that refresh). That isn't supported by the UI.
- Update: Some comments and other minor things.
- Update: Now supported by the GitHub actions
=> DB refresh: by `codeset_id`

.run/backend.run.xml, backend/routes/db.py
Something must have changed with one of our packages, maybe Starlette, or FastAPI, or Pydantic. Something is resulting in 'fastapi.exceptions.ResponseValidationError' on at least the route 'concept-ids-by-codeset-id'. Corrected the typedef for that route, and changed some other typedefs that didn't cause me errors, but I wondered if they might be safer just in case the code changes.
=> Bug fix: Type defs

enclave_wrangler/models.py, enclave_wrangler/objects_api.py
Follow-up from #836.
The cause of the bug ([GH action log](https://github.com/jhu-bids/TermHub/actions/runs/10670888366/job/29575743532)) is that a certain field was missing from the enclave object returned. Normally during `convert_row()`, if this happens, the `KeyError` is skipped. However, `convert_row()` behaves differently now when it is used by DB update functions, and I hadn't accounted for skipping past this `KeyError` in that case.
=> Bugfix: Fetch failures: `KeyError: 'parentVersionId'`

.github/workflows/backend_dev.yml, .github/workflows/backend_prod.yml, .github/workflows/test_frontend_e2e_live_dev.yml, .github/workflows/test_frontend_e2e_live_dev_running_local.yml, .github/workflows/test_frontend_e2e_live_prod.yml
Bug fix: GitHub action changes
- Update: GitHub deprecated certain actions that were being used by our actions: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/. Even though they were just deprecated, it caused an error from our actions still being on the old version.
=> Bug fix: GitHub action deprecated module

frontend/tests/playwright/comparison.todo.js, frontend/tests/playwright/n3c-recommended.todo.js, frontend/tests/utils.js, makefile
'Codeless' UI test generation
- Add: Makefile commands to use 'playright codegen'
- Add: New test file for N3C recommended (WIP)
- Add: frontend/tests/utils.js (refactored func into here from another file)
=> 'Codeless' UI test generation

frontend/src/components/CsetComparisonPage.jsx, frontend/src/state/AppState.jsx, frontend/src/state/GraphState.jsx
- Docs: Added / updated code comments
- Misc: Minor refactoring
=> Refactoring `displayRows` stuff, WIP - Joe comments & misc

backend/db/resolve_fetch_failures_0_members.py, backend/db/utils.py, enclave_wrangler/models.py, enclave_wrangler/objects_api.py
Sync Draft Expression Items
- Now syncing added or deleted expression items while csets are drafts or are finalized.
General
- Bug fix: When adding expression items, values for 'annotation' and 'sourceApplciation' fields were being dropped.
=> Sync Draft Expression Items

.github/workflows/refresh_voc.yml, .github/workflows/test_backend_e2e_and_unit_and_qc.yml, backend/db/refresh_dataset_group_tables.py
Vocab refresh
- Now errors when completes successfully so that it will notify that a restart of the server is necessary to refresh networkx graph.
Backend tests action
- Set cronjob to 1x/day, as this will test database integrity, including for vocab refreshes, which is helpful since due to the way I'm having it error and notify, it isn't running the test.
=> GH Action updates: Vocab refresh & Backend tests
