- enclave_wrangler/config.py
- enclave_wrangler/dataset_download.py
- enclave_wrangler/dataset_download_new_api.py
- requirements-unlocked.txt
- requirements.txt
Updates
```
Enclave Wrangler
- Dataset Download: (i) Minor various refactorings, (ii) Removed some code in CLI that looked like was not needed, (iii) Refactored functions into a EnclaveClient class, since they were sharing so several variables, (iv) link_types: Added basic request code, but still failing. WIP, (v) objects: Added this function. Added a bunch of TODOs. Currently having this save into termhub-csets/temp/. WIP.
Misc
- requirements: added (i) typeguard, (ii) pyarrow
termhub-csets
- Added a temp/ dir and popualted with some stuff downloaded from enclave. Contents of this will later be repurposed into datasets/.
```
> Dataset download updates

- frontend/src/CSets.js
- frontend/src/Table.js
Some final things I forgot to amend in my last commit before I merged.
```
TermHub Frontend
- Update: CsetComparisonChange: Some final touches I forgot to push in last PR
```
> Concept set comparison page: MVP (II)

- backend/db/full_data_refresh.py
Updates
```
- Add: CLI for full_data_refresh.py
```
> CLI for DB refresh

- README.md
biggest deal was noticing that the data is in submodules, and that you need to 'git submodule init' as well as 'git submodule update'
> README modification suggestions

- enclave_wrangler/actions_api.py
- enclave_wrangler/actions_old_palantir3file_api.py
- enclave_wrangler/datasets.py
- enclave_wrangler/objects_api.py
- enclave_wrangler/utils.py
- requirements-unlocked.txt
- requirements.txt
- test/test_enclave_wrangler.py
Updates
```
Backend
- Add: Refreshing of tables using objects API (WIP)
```
> DB refresh using `objects` API

- backend/db/initialize.py
- backend/db/load.py
- backend/db/utils.py
- db_initialize.py
- enclave_wrangler/objects_api.py
- enclave_wrangler/utils.py
Updates
```
DB Refresh / initialization
- Bugfix: indexes_and_derived_tables() was missing required 'schema' param
- Rename: /full_data_refresh.py -> db_initialize.py: Since that is what it is doing
- Bugfix: indexes_and_derived_tables(): Was erroring out when no datetime was present for last updated table vars
- Bugfix: load(): Was passing params in wrong order, resulting in crashed connection
- Add: A download_artefacts() func and some params for it to initialize() and load()
```
> DB Refresh / initialization

- .github/workflows/backend_dev.yml
- .github/workflows/backend_prod.yml
- .github/workflows/db_refresh_via_datasets.yml
- .github/workflows/frontend_dev.yml
- .github/workflows/frontend_prod.yml
- Added commit hash/branch printing to GitHub actions in case we need to roll back
> Github action rollback prints

- backend/app.py
- backend/routes/cset_crud.py
- backend/utils.py
- enclave_wrangler/utils.py
- frontend/src/UploadCsv.js
Updates
```
Universal error handling
- Update: Backend: Added a way such that all routes will return error message, including stack trace.
```
> Universal error handling

- frontend/src/App.js
- Bugfix: Frontend: Import of react-use/lib/useMeasure
> Bugfix: `useMeasure`

- backend/db/analysis.py
- backend/db/utils.py
- db_backup.sh
- makefile
Table counts
- Add: backend/db/analysis.py: Created this file and added count functions, as well as a CLI.
- Update: makefile: Added shortcuts to run analyses.
- Update: db_backup.sh: Updated instructions, and included steps to run new analysis.
- Update: backend/db/utils.py: Added list_tables()
> Table counts

- frontend/package-lock.json
- frontend/src/components/Csets.js
- frontend/src/components/CsetsDataTable.js
- frontend/src/components/MuiAppBar.js
- frontend/src/components/State.js
We fixed #334 and #325. They function as intended. #325 still has some styling issues.
> Dev jhu students temp

- test/test_backend.py
Updates
- Update: test_counts_compare_schemas() and test_counts_over_time(): (i) Added exceptions; some tables don't need counts, (ii) Added messages for when assertions fail
- Update: test_counts_over_time(): Only counting rows for all tables (other than exceptions) for
the newest run. This is because sometimes tables get added and removed, so there will be no counts for tables that did not exist at the time of previous runs.
> Counts tests follow-ups

- frontend/src/App.css
- frontend/src/pages/CsetComparisonPage.js
I think I resolved issue #330. However, this branch is out of sync with the develop branch, so that must be adjusted.
> Cset comparison col width

- test/test_backend.py
Test both as a function and as an endpoint
> Unit testing for the subgraph function

- backend/app.py
- backend/db/initialize.py
- backend/db/refresh.py
- backend/db/utils.py
- backend/routes/db.py
Currently the variables have been changed but the changes have not been tested, waiting for the ability to use the local database on computer.
> PR: 400 db refresh status variables

- backend/db/ddl-11-all_csets.jinja.sql
- backend/db/load.py
Updates
- Update: initialize: Now prints out time taken between each step running DDL
- Bugfix: initialze: DDL for all_csets table needed to use CASCADE with DROP.
> DDL updates / fixes

- test/test_backend.py
Added docstrings in order to utilize the unit tests for a variety of processes.
> PR: Test subgraph function and endpoint

- backend/db/refresh.py
- backend/db/resolve_fetch_failures.py
- backend/db/utils.py
- backend/routes/db.py
- enclave_wrangler/datasets.py
- enclave_wrangler/objects_api.py
- enclave_wrangler/utils.py
- startup.txt
- test/backend_tests/test_resolve_fetch_failures.py
- test/test_enclave_wrangler.py
1. An if statement to decide whether or not to run the program
2. If the program doesn't run variable is saved that instructs the program to run again
3. At the end of the program it checks the variable, deletes and runs the function again. 
So refresh() becomes recursive if the function is called while already running.
> Pull request: simultaneous db requests, calling backend directly

- backend/db/ddl-3-indexes.jinja.sql
- backend/db/refresh_voc_and_counts.py
Updates
- Update: DB refresh: vocab and counts tables: Added indexing of voc/counts tables
> Add indexing to voc/counts refresh

- .github/workflows/tests_and_qc_frontend.yml
- .gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/playwright.config.js
- frontend/src/components/Csets.js
- frontend/src/components/FlexibleContainer.js
- frontend/tests-examples/demo-todo-app.spec.js
- frontend/tests/tests.test.js
- makefile
Frontend testing
- Update: Installed playwright (updated .gitignore, package json)
- Add: Several playwright files: (i) test folders/scripts, (ii) GH action, (iii) config
> Frontend testing: initial setup

- .github/workflows/tests_and_qc_frontend.yml
Bugfix: Frontend tests GitHub action: It was using local webserver config which we are not requiring for this action at this time (satisfied with testing dev and prod).
>  Bug: Frontend test GH action broken

- backend/db/ad_hoc_omop_vocab_version.py
- backend/db/utils.py
- enclave_wrangler/objects_api.py
- Add: Scripting for populating omop vocab version
- Add: Function fetch_all_csets()
Also made some minor changes / comments.
> Populate omopVocabVersion in code_sets and derived tables #607

- backend/routes/graph.py
- test/test_backend/routes/tst_graph.py
Graph DB: Dynamic subgraphs
- Update: Abstracted function out of route
- Add: Test cases
> Dynamic subgraphs test

- .run/cli_ objects api - find missing.run.xml
- backend/routes/db.py
- docs/developer.md
- Update: n3c_comparison_rpt: Added caching
- Update: developer.md: Docs for renewing auth token
> n3c comparison report cache && auth token renewal docs

- backend/api_logger.py
- backend/db/queries.py
- backend/db/utils.py
- backend/routes/db.py
- backend/routes/oak.py
- enclave_wrangler/dataset_upload.py
- enclave_wrangler/objects_api.py
- test/test_backend/db/test_utils.py
Bugfix: Idle connections
- Bugfix: Closed much leaky code causing idle connections to appear.
- Add: Test for checking against acceptable threshold of idle connections.
General
- Add: Some docstrings
- Update: Some typing
Other
- Bugfix: get_cset_members_items(): Was re-doing the same query, undoing special conditional operations.
- Bugfix: get_concept_ids_by_codeset_id(): Was returning wrong data type when returning empty value.
- Delete: Removed duplicate route/function omop_id_from_concept_name()
> Bug: DB connection idling; soon no available connections

- backend/db/config.py
- backend/db/utils.py
- Bugfix: Derived table refresh status active indefinitely
- Update: Codestyle in db/utils.py
> Bugfix: Derived table refresh status active indefinitely

- backend/db/config.py
- backend/db/initialize.py
- backend/db/utils.py
- test/test_backend/db/tst_config.py
This is some stuff that I recently added to #577, but I moved here instead and did further updates. In spirit of how I've been doing things in Mondo, I've tried to make PRs more atomic. And it may be important to get some of these changes merged quickly in case #577 takes some more time.
Update DB config & add test
- Add: TestBackendDbConfig: Checks that DB config is in sync w/ DB
- Update: backend/db/config.py: Updated to keep current w/ state of DB, and added some functionality to
work with TestBackendDbConfig.
> Table dependency mapping updates

- backend/routes/graph.py
Test get_missing_in_between_nodes()
- Add: Test case for get_missing_in_between_nodes()
- Update: Typing for get_missing_in_between_nodes()
- Add: Ability to run the test if running file graph.py
https://app.diagrams.net/#G1mIthDUn4T1y1G3BdupdYKPkZVyQZ5XYR
> `get_missing_in_between_nodes()` test

- backend/routes/db.py
- backend/routes/graph.py
- test/test_backend/routes/tst_graph.py
- test/test_backend/test_backend.py
Graph refactoring
- Update: test_get_cset_members_items__cols(): Got test to pass
- Update: get_cset_members_items(): Raised err if conflicting params passed. Refactored. Now using safer injection of codeset IDs. Cleaned out dead code.
- Bugfix: get_cset_members_items(): Was not utilizing 'columns' and 'column' params.
- Update: filter_concepts(): Added a few params. Got it working.
- Add: test_graph(): Refactored out of concept_graph_post(), which is now a dumb route.
- Update: test_graph.py
- Delete: tst_indented_concept_list(): indented_concept_list() is now moved to frontend.
- Update: Various refactoring / codestyle / docstring updates
- Add: tst_concept_graph(): WIP
General
- Updated some type hints, made some codestyle changes, commented out some unused erroneous code.
> Frontend tree drawing - Joe

- backend/db/queries.py
- backend/db/utils.py
- backend/routes/graph.py
- test/test_backend/routes/tst_graph.py
Graph refactoring
- Update: get_missing_in_between_nodes(): Added 'verbose' param
- Update: concept_graph_post: Updated missing logic / returns
- Update: concept_graph(): Completed refactor. Now returns: subgraph (_post and _get return just its edges), IDs of missing in-betweens, dict of hidden IDs, by voc, IDs of nonstandard concepts hidden.
- Update: General: Code style, data types, misc.
- Update: tst_concept_graph(): Finished
> Frontend tree drawing - Joe(2)

- backend/db/utils.py
- makefile
- Add: CLI and makefile command to reset refresh state
> CLI: Reset refresh state

- makefile
Makefile help
- Update: Running 'make help' will now show documentation for all commands.
- Update: Updated PHONY goals to be correct
- Delete: Removed some unused commands
> Makefile help

- backend/db/resolve_fetch_failures_0_members.py
- backend/db/resolve_fetch_failures_excess_items.py
- Update: resolve_fetch_failures_0_members: Now does reset_temp_refresh_tables() if encounters exception.
- Update: resolve_fetch_failures_excess_items:
- Now does reset_temp_refresh_tables() if encounters exception.
- Add: Missing param: schema
> Resolve fetch failures: clean exception handling

- frontend/tests/basic-functions.test.js
- Bug fix: frontend/tests/basic-functions.test.js: Updated name - changed TermHub to VS-Hub
> Fix frontend tests: VS-Hub

- backend/db/ddl-14-concepts_with_counts.jinja.sql
- backend/db/initialize.py
- Update: DDL for concepts_with_counts
- Delete: commented out code dropping concepts_with_counts_ungrouped
> `initialize()` & DDL updates

- enclave_wrangler/objects_api.py
- makefile
- test/test_database.py
- Update: makefile goal: test-missing-csets. Now this test fails only if csets are older than 30 minutes.
> Update `make test-missing-csets`

- backend/db/initialize.py
- backend/db/load.py
- backend/db/refresh_from_datasets.py
Update initalize(): Dervied tables & more
- Update: code style
- Rename: indexes_and_derived_tables() --> make_derived_tables_and_more()
- Update: comment for make_derived_tables_and_more()
> Update initalize(): Dervied tables & more

- backend/db/refresh.py
- backend/db/resolve_fetch_failures_0_members.py
- enclave_wrangler/objects_api.py
- Bug fix: Discarded drafts cause error in fetch failures 0 members
- Bug fix: Runs fetch failures (if needed) in every instance of normal DB refresh running, even if the DB refresh detects that it does not need to run.
> Bug fixes: Discarded drafts & `fetch_failures_0_members`

- .github/workflows/refresh_db.yml
- backend/db/initialize.py
- backend/db/load.py
- backend/db/refresh.py
DB refresh: since
- Add: Support for YYYY-MM-DD. Previously needed full datetime timestamp with timezone offset.
- Add: GH action support
- Update: Misc refactoring
General
- Update: Misc refactoring of initalize() and similar. Comments.
> DB Refresh, `since` param support: GH action && `YYYY-MM-DD`

- backend/db/refresh.py
Update: DB Refresh: Remove 2 hour refresh buffer. Now no buffer. Just runs since the last time it exited.
- Update: Also made clarifying comment and cleaned up code to make 'end_time' more clear. Also changed its name to 'end_time_reported'.
> Remove refresh hours buffer

- backend/db/resolve_fetch_failures_0_members.py
- enclave_wrangler/objects_api.py
`resolve_fetch_failures_0_members()` updates
- Bugfix: Error message for failures showing incorrect list
- Update: rename param: runtime --> time_to_expand_threshold
- Update: Now errors out if fails to fetch members for non-draft, but only if it has been finalized longer than time_to_expand_threshold.
> `resolve_fetch_failures_0_members()`: Error only if cset > 2 hours

- backend/db/resolve_fetch_failures_0_members.py
- Bugfix: Cases where there were 0 expanded members because of the conditions 'isExcluded=true, includeDescendants=false, and includeMapped=false' were being reported as failures instead of being marked as resolved.
> `fetch_failures_0_members`: Resolve simple cases of 0 expanded members

- backend/routes/db.py
- frontend/src/components/AboutPage.jsx
Refresh button fixes
- Bug fix: Refresh button. I think was broken cuz was passing params that didn't exist on backend
- Update: Now runs GH action for refresh instead of running on server.
> Refresh button fixes

- backend/db/config.py
- test/test_backend/db/tst_config.py
- Update DB config w/ missing table relationships
- Update test_dependency_map(): Better error messaging
> Update DB config

- .github/workflows/test_backend_e2e_and_unit_and_qc.yml
- backend/app.py
- backend/db/analysis.py
- backend/db/config.py
- backend/db/utils.py
- backend/routes/cset_crud.py
- backend/routes/db.py
- backend/routes/graph.py
- backend/routes/oak.py
- enclave_wrangler/dataset_upload.py
- enclave_wrangler/datasets.py
- enclave_wrangler/reviving_ontology_api_stuff.py
- misc/ad_hoc/amia_paper_2024/stats.py
- test/test_backend/test_backend.py
- test/test_database.py
- test/test_enclave_wrangler/test_dataset_upload.py
- test/test_enclave_wrangler/test_objects_api.py
- test/utils.py
Fix backend tests
- Bug fixes: Erroring tests
- Bug fixes: Failing tests
- Update: misc comments / todos
> Fix backend tests

- backend/db/resolve_fetch_failures_excess_items.py
- backend/db/utils.py
- test/test_backend/db/test_utils.py
- test/test_backend/test_resolve_fetch_failures.py
Bugfix: Backend tests
- Bug fixes: Failing test_resolve_fetch_failures_excess_items() and FetchAuditTestRunner() tearDownClass assertion.
- Updates: Minor changes including param order, comments, and removing a print statement.
> Bugfix: Backend tests (2024-06-02)

- frontend/src/index.test.js
- frontend/src/state/GraphState.jsx
Bug fix: Jest tests
- Fixed a few syntax errors. Undefined reference errors mostly.
- Fixed a value name that was changed: isoalted --> unlinked
General
- Update: setOp(): Refactored part of this function into new func decomposeToArray()
> Bug fix: Jest unit tests

- .github/workflows/backend_dev.yml
- .github/workflows/backend_prod.yml
- .github/workflows/kill_idle_cons.yml
- .github/workflows/refresh_counts.yml
- .github/workflows/refresh_db.yml
- .github/workflows/refresh_from_datasets.yml
- .github/workflows/refresh_voc.yml
- .github/workflows/resolve_fetch_failures_0_members.yml
- .github/workflows/resolve_fetch_failures_excess_items.yml
- .github/workflows/test_backend_e2e_and_unit_and_qc.yml
GH actions: Fewer installs
- Deactivated install --upgrade of pip, wheel, and setuptools, as this probably decreases stability moreso than increases.
> GH Actions: Fewer installs

- .github/workflows/backend_dev.yml
- .github/workflows/backend_prod.yml
- .github/workflows/kill_idle_cons.yml
- .github/workflows/refresh_counts.yml
- .github/workflows/refresh_db.yml
- .github/workflows/refresh_from_datasets.yml
- .github/workflows/refresh_voc.yml
- .github/workflows/resolve_fetch_failures_0_members.yml
- .github/workflows/resolve_fetch_failures_excess_items.yml
- .github/workflows/test_backend_e2e_and_unit_and_qc.yml
- enclave_wrangler/utils.py
- install-requirements.sh
- requirements-unlocked.txt
- requirements.txt
Was getting deployment error. Juice not worth squeeze.
> Disable OAuth

- backend/db/utils.py
Bug fix: Issue dropping a table during refresh w/ dependent tables & no CASCADE
> Bug: Refresh fails; Dropping `concept` table?

- .github/workflows/test_frontend_e2e_live_dev.yml
- .github/workflows/test_frontend_e2e_live_dev_running_local.yml
- .github/workflows/test_frontend_e2e_live_prod.yml
- makefile
Playwright GitHub actions refactor
- Delete: Old GitHub action combining dev and prod
- Add: Production GH action that tests on prod using the code / playwright tests that were written at the time prod was deployed.
- Add: Develop GH action that tests on dev using the code / playwright tests that
were written at the time dev was deployed.
- Add: Develop ("local") GH action that tests on dev using the code / playwright tests that from the develop branch, reflecting our most recent local changes.
- Update: Makefile commands to work w/ these updated actions.
> Playwright actions

- docs/developer.md
Deployment docs update
- Update: Docs related to new procedures for updating tags related to keeping GH actions in sync.
> Deployment docs update

- backend/db/utils.py
- test/test_enclave_wrangler/test_objects_api.py
Bug fix: DB refresh table order
- Fixed bug where order of derived tables refreshed was non-deterministic and wrong.
> Bug fix: DB refresh table order

- .github/workflows/test_frontend_e2e_live_dev_running_local.yml
- .gitignore
- frontend/tests/playwright/basic-functions.test.js
- frontend/tests/playwright/large-cset-handling.test.js
Bug fix: Playwright tests
- Fix: link title: 'cset comparison' --> 'analyze and author'
- Fix: data-testid: 'cset comparison' --> 'analyze and author'
- Update: .gitignore: To reference changed path of playwright test performance results CSVs.
> Bug fix: Playwright tests

- backend/db/resolve_fetch_failures_0_members.py
Bug fix: 'fetch failures excess items' cases occurring during draft reconciliation script
> Bug fix: Excess members

- docs/developer.md
Updated these docs for DB refresh, counts refresh, and vocab refresh
> Docs: DB refresh

- README.md
- docs/developer.md
- docs/refresh.md
- docs/refresh_failure_history.md
Docs updates
- Add: refresh.md: Moved some docs from developer.md into here, and elaborated.
- Add: refresh_failure_history.md: Data Joe has been taking for the last year or more about GitHub action failures that are outside of our control.
- Update: developer.md
> Docs updates (refresh & refresh errors)
